language: python
python:
- "3.6"

# command to install dependencies
install:
- sudo pip3 install "molecule[lint]"
- sudo pip3 install "molecule[docker]"

# command to run tests
script:
- ansible-lint install/*.yml -x 303,701,601,206,602,403,301,502,306 -v
- molecule --version
- ansible --version
- sudo molecule test

