---
- remote_user: root
  gather_facts: no
  hosts: server
  vars:
    - gluster_maintenance_old_node: host1.example.com
    - gluster_maintenance_new_node: host1.example.com
    - gluster_maintenance_cluster_node: host2.example.com
  roles:
    - gluster.maintenance

