---
# Set up the volume management
- name: Fetch the directory and volume details
  block:
    - name: Get the list of volumes on the machine
      shell: ls "{{ glusterd_libdir }}/vols"
      register: dir_list

    - set_fact:
        volumes: "{{ dir_list.stdout.split() }}"

    # Find the list of bricks on the machine
    - name: Get the list of bricks corresponding to volume
      shell: >
        gluster vol info {{ item }} | grep {{ gluster_maintenance_old_node }} |
        awk -F: '{ print $3 }'
      with_items: "{{ volumes }}"
      register: brick_list

  delegate_to: "{{ gluster_maintenance_cluster_node }}"
  
- name: Run replace-brick commit on the brick
  shell: >
    gluster volume replace-brick {{ item.0.item }}
    {{gluster_maintenance_old_node}}:{{item.1}}
    {{gluster_maintenance_new_node}}:{{item.1}}
    commit force
  with_subelements: 
    - "{{ brick_list.results }}"
    - stdout_lines
  delegate_to: "{{ gluster_maintenance_cluster_node }}"
